VM translator part 1
empathy87/hdk pull request #3
Opened 2023-05-02 12:43 UTC by gaskov-miron

2023-05-02 13:01 UTC, empathy87 commented on hdk/virtual_machine/syntax.py
> +class StackInstruction:
Rename this class to ArithmeticLogicalCommand. And change the docstring to "Represents arithmetic and logical commands." Try not to use expressions in docstrings line "A data class representing". It takes more space and doesn't give additional information. It is obvious that it is a data class.

2023-05-02 13:05 UTC, empathy87 commented on hdk/virtual_machine/syntax.py
> +class MemoryAccessInstruction:
Rename this class to MemoryTransferCommand and change the docstring to start with "Represents...".

2023-05-02 13:13 UTC, empathy87 commented on hdk/virtual_machine/syntax.py
> +    index: str
Change the type of index to int.

2023-05-02 13:14 UTC, empathy87 commented on hdk/virtual_machine/syntax.py
> +    def __post_init__(self):
Add a check that the index is non-negative.

2023-05-02 13:15 UTC, empathy87 commented on hdk/virtual_machine/syntax.py
> +Instruction: TypeAlias = StackInstruction | MemoryAccessInstruction
Rename Instruction to VMCommand

2023-05-02 13:16 UTC, empathy87 commented on hdk/virtual_machine/parser.py
> +"""Functions for parsing symbolic instructions into their underlying fields."""
Instead of "symbolic instruction" write "virtual machine commands"

2023-05-02 13:26 UTC, empathy87 commented on hdk/virtual_machine/parser.py
> +def remove_comment(line: str) -> str:
Remove this function. You don't need it. In VM language only comment lines starting with // are allowed. In such cases the whole line is a comment. Comments in other places are not allowed.

2023-05-02 13:27 UTC, empathy87 commented on hdk/virtual_machine/parser.py
> +def remove_whitespaces(line: str) -> str:
Remove this function. You don't need it. The split function will take care of different kind of whitespaces.

2023-05-02 13:28 UTC, empathy87 commented on hdk/virtual_machine/parser.py
> +def clean_line(line: str) -> str:
Remove this function.

2023-05-02 13:28 UTC, empathy87 commented on hdk/virtual_machine/parser.py
> +        command, segment, idx = instruction_text.split()
Convert idx to int right here.

2023-05-02 13:30 UTC, empathy87 commented on hdk/virtual_machine/vm.py
> +        preprocessed_line = clean_line(line)
Don't clean line.

2023-05-02 13:32 UTC, empathy87 commented on hdk/virtual_machine/vm.py
> +        if len(preprocessed_line) == 0:
Change this if to
if len(line.strip()) == 0 or line.startswith("//"):

2023-05-02 13:36 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +def translate(instructions: Iterable[Instruction]) -> Iterator[list[str]]:
Change the result to Iterator[str], not Iterator[list[str]]. In order to do it, change yield asm_code to yield from asm_code.

2023-05-02 13:37 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +            yield asm_code
Change to yield from asm_code

2023-05-02 13:37 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +            yield translate_memory_access_instruction(instruction)
change to yield from ...

2023-05-03 06:00 UTC, gaskov-miron reviewed
submit

2023-05-03 06:00 UTC, gaskov-miron commented
submit

2023-05-03 06:00 UTC, gaskov-miron commented
submit

2023-05-03 06:27 UTC, empathy87 requested changes

2023-05-03 06:27 UTC, empathy87 commented on hdk/virtual_machine/vm.py
> +            for assembly_code_line in assembly_code_list:
You don't need the inner cycle here.

2023-05-03 06:27 UTC, empathy87 commented on hdk/virtual_machine/syntax.py
> +Instruction: TypeAlias = ArithmeticLogicalCommand | MemoryTransferCommand
Rename Instruction to command here.

2023-05-03 06:27 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +def translate_stack_instruction(
Don't return instruction counter back. Make command_id a parameter, which indicates the number of order number of command in the VM program.

2023-05-03 06:27 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +    label_counter = 0
Remove label_counter variable.

2023-05-03 06:27 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +    for instruction in instructions:
Change the loop to 
for command_id, command in commands:

2023-05-03 06:27 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +            asm_code, label_counter = translate_stack_instruction(
Send command_id instead of label_counter.

2023-05-03 06:27 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +def translate_stack_instruction(
Rename to translate_arithmetic_locical_command. Change parameter name to command instead of stack_instruction.

2023-05-03 06:27 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +def translate_memory_access_instruction(m: MemoryTransferCommand) -> list[str]:
Rename to translate_memory_transfer_command. Change parameter name from m to command.

2023-05-03 06:27 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +    if m.command == "push":
Split the function into two different functions: translate_push_command and translate_pop_command.

2023-05-03 06:27 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +def translate(instructions: Iterable[Instruction]) -> Iterator[str]:
Change instructions parameter name to commands.

2023-05-03 07:18 UTC, gaskov-miron reviewed
submit

2023-05-03 07:18 UTC, gaskov-miron commented
submit

2023-05-03 08:00 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +    def pop_to_r13() -> list[str]:
Change pop_to_r13 function into _RESTORE_D_INSTRUCTIONS (find the appropriate name) constant on the module level.

2023-05-03 08:01 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +    """Translates a sequence of instructions into a sequence of assembly code lists.
-> Translate VM-commands into assembly symbolic instructions.

2023-05-03 08:02 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +        commands: An iterable of instructions to be translated.
-> ... of commands...

2023-05-03 08:03 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +        list[str]: Lists of strings representing the assembly code for each instruction.
Don't use list[str] style for Yields:.
Fix the docstring according.

2023-05-03 08:41 UTC, gaskov-miron reviewed
submit

2023-05-03 08:58 UTC, empathy87 requested changes

2023-05-03 08:58 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +        command (StackInstruction): The stack instruction to translate.
Remove information in brackets. The docstring style is the following:
Args:
       arg_name: Arg description.

Also change the descriptions to reflect the names of arguments.

2023-05-03 08:58 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +         a list of assembly code instructions and the updated instruction counter value.
Start with the capital A.

2023-05-03 08:58 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +        code = [
No need of variable code.

2023-05-03 08:58 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +    else:
No need of else.

2023-05-03 08:58 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +        raise ValueError(f"Invalid command {command.operation!r} for stack instruction")
-> Invalid operation ... for arithmetic logical command.

2023-05-03 08:58 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +def translate_push(command: MemoryTransferCommand) -> list[str]:
Add the docstring.

2023-05-03 08:58 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +def translate_push(command: MemoryTransferCommand) -> list[str]:
Change argument command to two arguments: segment and index.

2023-05-03 08:58 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +    return [f"@{command.index + 16}", "D=M"]
It is hard to understand, what kind of segment is translated in the last return statement. Change it to 
if segment == ...:
   return [f"@{....]
raise ValueError....

2023-05-03 08:58 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +def translate_pop(command: MemoryTransferCommand) -> list[str]:
change command argument to two arguments: segment and index. Add a docstring.

2023-05-03 08:58 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +    return [f"@{command.index + 16}", "D=A", "@R13", "M=D"]
Change it to:
if segment == ...
   return
raise ValueException

2023-05-03 08:58 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +        str: String representing the assembly code for each command.
Remove str: from yields. Yields as a Returns should contain simple description without xxx:

2023-05-03 09:36 UTC, gaskov-miron reviewed
submit

2023-05-03 10:26 UTC, empathy87 requested changes

2023-05-03 10:26 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +"""Provides functions to translate VM commands into their assembly commands."""
-> ... their assembly instructions.

2023-05-03 10:26 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +        code = [
Remove local variable code.

2023-05-03 10:26 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +         A list of assembly code instructions and the updated instruction counter value.
There is no instruction counter value.

2023-05-03 10:26 UTC, empathy87 commented on hdk/virtual_machine/code.py
> +        String representing the assembly code for each command.
-> Strings ...

2023-05-03 10:46 UTC, empathy87 approved these changes

2023-05-03 10:47 UTC, merged